#ifndef __PHYMEM_H
#define __PHYMEM_H
#define dwIOCTL_TYPE 40000 
#define dwIOCTL_READ_MSR	CTL_CODE( dwIOCTL_TYPE  , 0x821,  METHOD_BUFFERED, FILE_ANY_ACCESS)
#define nIA32_TEMPERATURE_TARGET 0x01A2
#define nIA32_THERM_STATUS_MSR 0x019C

#endif	//__PHYMEM_H
